/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'chips' : IDL.Null,
  'drink' : IDL.Null,
  'energy' : IDL.Null,
});
export const Cents = IDL.Nat;
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'emoji' : IDL.Text,
  'category' : Category,
  'price' : Cents,
});

export const idlService = IDL.Service({
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'chips' : IDL.Null,
    'drink' : IDL.Null,
    'energy' : IDL.Null,
  });
  const Cents = IDL.Nat;
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'emoji' : IDL.Text,
    'category' : Category,
    'price' : Cents,
  });
  
  return IDL.Service({
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };